// Generated by Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import UserNotifications;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="winguSDKEssential",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


/// <code>Component</code> is a base class for all elements configurable inside wingu portal. It represents single object created inside your content.<br/>
/// The base <code>Component</code> object shouldn’t be used or created directly.
SWIFT_CLASS("_TtC17winguSDKEssential9Component")
@interface Component : NSObject
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Action Component is element that trigger redirection from the deck. Currently support types are listed under <code>ActionComponent.ActionType</code> section<br>
/// Example view generated using this component will look like this:
/// <img src="../docs_assets/ActionComponent.png" alt="Action Component"/>
/// Where you can change parameters like corner radius, fonts and colors.
SWIFT_CLASS("_TtC17winguSDKEssential15ActionComponent")
@interface ActionComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface ActionComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (ActionComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






/// Contain informations about address in readable format. Usually associated with <code>Location</code> object.
SWIFT_CLASS("_TtC17winguSDKEssential7Address")
@interface Address : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface Address (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Address * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Contains information about image and it’s alignment.
SWIFT_CLASS("_TtC17winguSDKEssential14AlignmentImage")
@interface AlignmentImage : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface AlignmentImage (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (AlignmentImage * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Contains information about text alignment.
SWIFT_CLASS("_TtC17winguSDKEssential13AlignmentText")
@interface AlignmentText : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface AlignmentText (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (AlignmentText * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Contains information about album that is associated with mp3 file imported to wingu portal.<br>
/// This will filled up with ID3 (or ID3v2) tags from mp3 file.
SWIFT_CLASS("_TtC17winguSDKEssential10AudioAlbum")
@interface AudioAlbum : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface AudioAlbum (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (AudioAlbum * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Describes information about media inside <code>AudioPlaylistComponent</code><br/>
/// By default it’s mp3 files and some parameters (ex. <code>album</code>) is based on mp3 tags. Some of them are fetched from wingu portal (ex. <code>name</code>)
SWIFT_CLASS("_TtC17winguSDKEssential10AudioMedia")
@interface AudioMedia : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface AudioMedia (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (AudioMedia * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Match Audio Component configurable in wingu portal. <br/>
/// <img src="../docs_assets/AudioPlaylistComponent.png" alt="Audio Playlist Component"/><br/>
/// This is a collection of mp3 playable whenever <code>Deck</code> is on screen. It’s partially based on mp3 ID3 tags and partially on configuration in wingu portal.
SWIFT_CLASS("_TtC17winguSDKEssential22AudioPlaylistComponent")
@interface AudioPlaylistComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface AudioPlaylistComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (AudioPlaylistComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






/// Representation of available languages for content.
SWIFT_CLASS("_TtC17winguSDKEssential18AvailableLanguages")
@interface AvailableLanguages : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface AvailableLanguages (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


@interface AvailableLanguages (SWIFT_EXTENSION(winguSDKEssential))
/// Saving object permanently to device.<br/>
/// It will create a storage if not existed before accessible by <code>AvailableLanguages.saved()</code>
- (BOOL)saveAndReturnError:(NSError * _Nullable * _Nullable)error;
/// Remove given object from internal storage.<br/>
- (BOOL)removeAndReturnError:(NSError * _Nullable * _Nullable)error;
@end


/// Contains information about background color.
SWIFT_CLASS("_TtC17winguSDKEssential10Background")
@interface Background : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface Background (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Background * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Typically associated with CouponComponent object. Represent barcode that can be scanned using other readers.
SWIFT_CLASS("_TtC17winguSDKEssential7Barcode")
@interface Barcode : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface Barcode (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Barcode * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Base representation of some wingu trigger configured in portal. All detailed triggers like <code>Geofence</code> or <code>Beacon</code> will inherit from this class.<br/>
/// Detailed information about triggers can be found in class specific for every type. This class contain parameters related to wingu portal or time of discovery.</br>
/// <blockquote>
/// <em>Note:</em> All delegates method will always return <code>Channel</code> or collection of <code>Channel</code> even if you monitor only for one type.
///
/// </blockquote>
/// However object of this class without subclass cannot be used for anything inside wingu SDK. Initialization should be avoided and all method will map to one of the supported subclass.<br/>
/// <img src="../docs_assets/Channel.png" alt="Channel"/></br>
/// <code>Pack</code> collection for multilanguage is not supported with current version of the SDK. It will be returned always with end-user device language whenever your configured content on wingu portal supports it.
SWIFT_CLASS("_TtC17winguSDKEssential7Channel")
@interface Channel : NSObject
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Representation of <code>CoreLocation</code> class <code>CLBeacon</code> with extra arguments from wingu portal.<br/>
/// This class combines fetched arguments from wingu portal such as <code>Deck</code>, <code>Pack</code>, <code>Content</code> and match it with physical characteristic of the beacon. All parameters from <code>CLBeacon</code> will be matched with the same naming to this class.<br/>
/// <blockquote>
/// <em>Note</em>: This is not extend or override any <code>CLBeacon</code> parameters. Any changes in object of this class will not take any effect in physical beacon!<br/>
///
/// </blockquote>
/// This class is marked as <code>final</code>, this shouldn’t need subclassed. If there is a need to change minor/major/uuid of physical beacon this should be done with beacons manufacturer dedicated application or SDK.
SWIFT_CLASS("_TtC17winguSDKEssential6Beacon")
@interface Beacon : Channel
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end










@interface Beacon (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


@interface Beacon (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Beacon * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






@interface Beacon (SWIFT_EXTENSION(winguSDKEssential))
/// Saving object permanently to device.<br/>
/// It will create a storage if not existed before accessible by <code>Beacon.saved()</code>
- (BOOL)saveAndReturnError:(NSError * _Nullable * _Nullable)error;
/// Remove given object from internal storage.<br/>
- (BOOL)removeAndReturnError:(NSError * _Nullable * _Nullable)error;
@end


/// Layer of abstraction for <code>CoreLocation</code> ranging & monitoring iBeacons. This is build using Singleton principle. There will never be a need to use more than one instance of <code>BeaconScanner</code> to work with wingu beacons. By default regions to monitor and ranging are equal and default wingu regions apply if not specyfied otherwise.
SWIFT_CLASS("_TtC17winguSDKEssential13BeaconScanner")
@interface BeaconScanner : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




/// Associated with <code>Geofence</code>. Contains values that descibe specyfic area created in wingu portal.<br/>
/// Usually it’s 5 coordinates in collection from SE to SW clockwise and close the shape.
/// <img src="../docs_assets/Boundaries.gif" alt="Boundaries"/></br>
/// Check all available types in <code>BoundaryType</code> enum.
SWIFT_CLASS("_TtC17winguSDKEssential8Boundary")
@interface Boundary : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface Boundary (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Boundary * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// BrandBarComponent is a representation of Brand bar created in wingu portal.<br/>
/// Brand bar allow to put text and image.
SWIFT_CLASS("_TtC17winguSDKEssential17BrandBarComponent")
@interface BrandBarComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface BrandBarComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (BrandBarComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end












/// Defines position of components inside <code>Deck</code>.
SWIFT_CLASS("_TtC17winguSDKEssential4Card")
@interface Card : NSObject
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface Card (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Card * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end









@interface Channel (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Channel * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


@interface Channel (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end






@interface Channel (SWIFT_EXTENSION(winguSDKEssential))
/// Saving object permanently to device.<br/>
/// It will create a storage if not existed before accessible by <code>Channel.saved()</code>
- (BOOL)saveAndReturnError:(NSError * _Nullable * _Nullable)error;
/// Remove given object from internal storage.<br/>
- (BOOL)removeAndReturnError:(NSError * _Nullable * _Nullable)error;
@end













@interface Component (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


@interface Component (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Component * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// It is a representation of info card in wingu portal. It may look like this:<br/>
/// <img src="../docs_assets/ContactComponent.png" alt="Contact Component"/></br>
/// It is possible to store all information in iOS default <code>Contacts</code> app, however there is need to add <code>NSContactsUsageDescription</code> in <code>Info.plist</code> file.
/// <blockquote>
/// <em>Note:</em> iOS 11+ will raise any helpful flag and simply app will crash in case of missing key in <code>Info.plist</code> file mentioned above.
///
/// </blockquote>
/// By default all links will be <code>https</code> ready from wingu portal if not specified otherwise.
SWIFT_CLASS("_TtC17winguSDKEssential16ContactComponent")
@interface ContactComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface ContactComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (ContactComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






/// Contain detail information about address split into different field<br/>
/// This should help show address using Maps app directly from <code>ContactComponent</code>.
SWIFT_CLASS("_TtC17winguSDKEssential23ContactComponentAddress")
@interface ContactComponentAddress : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface ContactComponentAddress (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (ContactComponentAddress * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Social Media references. In Contacts apps there are facebook, twitter and yelp already natively supported. Google + will be transfered to plain texts or skipped, since there is no support for it in OS level.
SWIFT_CLASS("_TtC17winguSDKEssential18ContactSocialMedia")
@interface ContactSocialMedia : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface ContactSocialMedia (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (ContactSocialMedia * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Contains informations about components configured in wingu portal and languages that it’s available.
/// <blockquote>
/// <em>Note:</em> There is no need to manually selected languages. It will automatically match device preferences.
///
/// </blockquote>
/// There is possible that <code>Channel</code> object can exist without content. Force casting is hightly unrecommended.
SWIFT_CLASS("_TtC17winguSDKEssential7Content")
@interface Content : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface Content (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Content * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end




/// This is a representation of menu item content.
SWIFT_CLASS("_TtC17winguSDKEssential17ContentOfMenuItem")
@interface ContentOfMenuItem : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface ContentOfMenuItem (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (ContentOfMenuItem * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// CouponComponent works with <code>Barcode</code> to provide reach experience. It may look like this:
/// <img src="../docs_assets/CouponComponent.png" alt="Coupon Component"/></br>
/// Barcode generation happen on OS level using <code>Machine Readable Object Types</code> such as EAN-13. To learn more visit <a href="https://developer.apple.com/documentation/avfoundation/avmetadataobject.objecttype/1618807-ean13">Official Apple Documentation</a>
/// Coupon is entirely configurable in wingu portal
SWIFT_CLASS("_TtC17winguSDKEssential15CouponComponent")
@interface CouponComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface CouponComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (CouponComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






@interface CouponComponent (SWIFT_EXTENSION(winguSDKEssential))
/// Saving object permanently to device.<br/>
/// It will create a storage if not existed before accessible by <code>CouponComponent.saved()</code>
- (BOOL)saveAndReturnError:(NSError * _Nullable * _Nullable)error;
/// Remove given object from internal storage.<br/>
- (BOOL)removeAndReturnError:(NSError * _Nullable * _Nullable)error;
@end




/// Contains information about all components and cards. This is a representation of an object created in wingu portal. This is already localized to match device selected language.
SWIFT_CLASS("_TtC17winguSDKEssential4Deck")
@interface Deck : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface Deck (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Deck * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end




/// Collection of files added in wingu portal.
SWIFT_CLASS("_TtC17winguSDKEssential13FileComponent")
@interface FileComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface FileComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (FileComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end








/// Answer for a question in <code>FormComponent</code>.
SWIFT_CLASS("_TtC17winguSDKEssential10FormAnswer")
@interface FormAnswer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


/// Form/Survey component. Representation of component with a same name in wingu portal<br/>
SWIFT_CLASS("_TtC17winguSDKEssential13FormComponent")
@interface FormComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface FormComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (FormComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


@interface FormComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end








@interface FormComponent (SWIFT_EXTENSION(winguSDKEssential))
/// Saving object permanently to device.<br/>
/// It will create a storage if not existed before accessible by <code>FormComponent.saved()</code>
- (BOOL)saveAndReturnError:(NSError * _Nullable * _Nullable)error;
/// Remove given object from internal storage.<br/>
- (BOOL)removeAndReturnError:(NSError * _Nullable * _Nullable)error;
@end


/// Form component element. Available types:<br/>
/// <ul>
///   <li>
///     Text<br/>
///   </li>
///   <li>
///     Link<br/>
///   </li>
///   <li>
///     Email<br/>
///   </li>
///   <li>
///     Date/Time<br/>
///   </li>
///   <li>
///     Dropdown<br/>
///   </li>
///   <li>
///     Checkbox<br/>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC17winguSDKEssential11FormElement")
@interface FormElement : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface FormElement (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (FormElement * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end




/// Resubmit values from form component
SWIFT_CLASS("_TtC17winguSDKEssential12FormResubmit")
@interface FormResubmit : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface FormResubmit (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (FormResubmit * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Form select options. Only valid with selections
SWIFT_CLASS("_TtC17winguSDKEssential16FormSelectOption")
@interface FormSelectOption : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface FormSelectOption (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (FormSelectOption * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end




/// Gallery Component contain both single images inline in text and multiple pictures.
/// Images are not directly accessible from <code>GalleryComponent</code>, they’re wrapped in <code>WinguImage</code> and plain <code>Image</code> classes.
SWIFT_CLASS("_TtC17winguSDKEssential16GalleryComponent")
@interface GalleryComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface GalleryComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (GalleryComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






/// Representation of geofence area from wingu portal, Configurable in wingu portal contains usually already prepared content, without extra fetches (like in a case of iBeacon).<br/>
/// In case of missing content in geofence by default it will not be shown in <code>WinguLocations</code> and will not be returned through delegate methods.
SWIFT_CLASS("_TtC17winguSDKEssential8Geofence")
@interface Geofence : Channel
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface Geofence (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Geofence * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


@interface Geofence (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end






@interface Geofence (SWIFT_EXTENSION(winguSDKEssential))
/// Saving object permanently to device.<br/>
/// It will create a storage if not existed before accessible by <code>Geofence.saved()</code>
- (BOOL)saveAndReturnError:(NSError * _Nullable * _Nullable)error;
/// Remove given object from internal storage.<br/>
- (BOOL)removeAndReturnError:(NSError * _Nullable * _Nullable)error;
@end


/// Scanner for geofences. It shared some behaviours from <code>BeaconScanner</code> whenever it makes sense.<br/>
/// <code>GeofenceScanner</code> manage geofences for both background and foreground app state.
SWIFT_CLASS("_TtC17winguSDKEssential15GeofenceScanner")
@interface GeofenceScanner : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Contains informations about image.
/// For managing images wingu is using <a href="https://cloudinary.com">Cloudinary</a>. In this case <code>uID</code> will contain id of a picture in cloudinary.
SWIFT_CLASS("_TtC17winguSDKEssential5Image")
@interface Image : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface Image (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Image * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Contains information about image before download
SWIFT_CLASS("_TtC17winguSDKEssential13ImageMetadata")
@interface ImageMetadata : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface ImageMetadata (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (ImageMetadata * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// As a part of analytics interaction is a representation of single event happen in <code>Channel</code> or <code>Content</code>.<br/>
/// It’s automatically triggered by this library or Content library.<br/>
SWIFT_CLASS("_TtC17winguSDKEssential11Interaction")
@interface Interaction : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end








/// Location of the channel. Usually connected to <code>Channel</code> object and depends of channel type (<code>Geofence</code>, <code>Beacon</code>…). Please note that any of this fields can be <code>nil</code>.
SWIFT_CLASS("_TtC17winguSDKEssential8Location")
@interface Location : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface Location (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Location * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Location Component is a representation of wingu portal Map.<br/>
/// <img src="../docs_assets/LocationComponent.png" alt="Location Component"/></br>
/// This component using standard <code>CoreLocation</code> method and arguments and it’s <em>always</em> a circle.
SWIFT_CLASS("_TtC17winguSDKEssential17LocationComponent")
@interface LocationComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface LocationComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (LocationComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






/// Contains information about menu item and assigned content. This is a representation of an object created in wingu portal.
SWIFT_CLASS("_TtC17winguSDKEssential8MenuItem")
@interface MenuItem : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface MenuItem (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (MenuItem * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Allows you to receive <code>Notifications</code> through wingu platform.<br/>
/// <blockquote>
/// <em>Note:</em> wingu not sending push notifications only whenever near <code>Channel</code>. There is no need to configure Apple Developer Certificate to handle Push Notification when app does not support it.<br/>
/// wingu SDK is using <code>UserNotifications</code> framework<br/>
///
/// </blockquote>
/// In order to receive notifications there might be different action required for different <code>Channel</code> type.<br/>
SWIFT_CLASS("_TtC17winguSDKEssential20NotificationsManager")
@interface NotificationsManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UNUserNotificationCenter;
@class UNNotification;
@class UNNotificationResponse;

@interface NotificationsManager (SWIFT_EXTENSION(winguSDKEssential)) <UNUserNotificationCenterDelegate>
/// :nodoc:
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center willPresentNotification:(UNNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(UNNotificationPresentationOptions))completionHandler;
/// :nodoc:
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center didReceiveNotificationResponse:(UNNotificationResponse * _Nonnull)response withCompletionHandler:(void (^ _Nonnull)(void))completionHandler;
@end


/// Contains already localized <code>Deck</code> with <code>Card</code> collection.
SWIFT_CLASS("_TtC17winguSDKEssential4Pack")
@interface Pack : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface Pack (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Pack * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Usually associated with a <code>Deck</code> and contains information about language of the <code>Deck</code>.
SWIFT_CLASS("_TtC17winguSDKEssential10PackLocale")
@interface PackLocale : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface PackLocale (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (PackLocale * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


@interface PackLocale (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// Contain information about deck arrangement.
SWIFT_CLASS("_TtC17winguSDKEssential8Position")
@interface Position : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface Position (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (Position * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Representation of rating from wingu portal.<br/>
/// The values 0-5 are fixed and cannot be changed.
SWIFT_CLASS("_TtC17winguSDKEssential15RatingComponent")
@interface RatingComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface RatingComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (RatingComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






@interface RatingComponent (SWIFT_EXTENSION(winguSDKEssential))
/// Saving object permanently to device.<br/>
/// It will create a storage if not existed before accessible by <code>RatingComponent.saved()</code>
- (BOOL)saveAndReturnError:(NSError * _Nullable * _Nullable)error;
/// Remove given object from internal storage.<br/>
- (BOOL)removeAndReturnError:(NSError * _Nullable * _Nullable)error;
@end


/// Channels that already has been visited. Works in companion to delegate method that returns only unseen channels in <code>WinguLocationsDelegate</code><br/>
/// Visit <code>WinguLocationsDelegate</code> for more information what “unseen” can mean.<br/>
/// This works automatically from winguSDKContent.<br/>
SWIFT_CLASS("_TtC17winguSDKEssential12SeenChannels")
@interface SeenChannels : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface SeenChannels (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


@interface SeenChannels (SWIFT_EXTENSION(winguSDKEssential))
/// Saving object permanently to device.<br/>
/// It will create a storage if not existed before accessible by <code>SeenChannels.saved()</code>
- (BOOL)saveAndReturnError:(NSError * _Nullable * _Nullable)error;
/// Remove given object from internal storage.<br/>
- (BOOL)removeAndReturnError:(NSError * _Nullable * _Nullable)error;
@end


/// Representation of separator components in wingu portal.<br/>
/// There is couple of styles of components to be picked, but all should be set in portal.<br/>
/// Type here should be threated as read-only and shouldn’t be overriden.
SWIFT_CLASS("_TtC17winguSDKEssential18SeparatorComponent")
@interface SeparatorComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface SeparatorComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (SeparatorComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






/// Survey Monkey component redirect to form of the survey. This is representation of component with a same name in wingu portal.<br/>
/// It is not possible to configure fullscreen. Component only shows preview and redirect to <code>WKWebView</code> that shows fullscreen survey using Survey Monkey responsive version of the website.
SWIFT_CLASS("_TtC17winguSDKEssential21SurveyMonkeyComponent")
@interface SurveyMonkeyComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface SurveyMonkeyComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (SurveyMonkeyComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






/// TextComponent is a representation of Markdown or HTML component created in wingu portal.
SWIFT_CLASS("_TtC17winguSDKEssential13TextComponent")
@interface TextComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface TextComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (TextComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end




















/// Video component is a representation of component from wingu portal.<br/>
/// It’s usually youtube and shown with provided by Google component with trademark and with iframe.</br>
SWIFT_CLASS("_TtC17winguSDKEssential14VideoComponent")
@interface VideoComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface VideoComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (VideoComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






/// Component that trigger third party action from connected website configured in wingu portal<br/>
/// It connects automatically to API and trigger action.
SWIFT_CLASS("_TtC17winguSDKEssential16WebhookComponent")
@interface WebhookComponent : Component
/// :nodoc:
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface WebhookComponent (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (WebhookComponent * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end






/// Single file object associated with <code>FileComponent</code>.
SWIFT_CLASS("_TtC17winguSDKEssential9WinguFile")
@interface WinguFile : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface WinguFile (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (WinguFile * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Wrap <code>Image</code> object to provide necessery information about picture before start download.<br/>
/// This class will provide dimensions of selected picture and position among other ones. Position existance in this class usually indicates relation with <code>GalleryComponent</code>
SWIFT_CLASS("_TtC17winguSDKEssential10WinguImage")
@interface WinguImage : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface WinguImage (SWIFT_EXTENSION(winguSDKEssential))
/// :nodoc:
+ (WinguImage * _Nullable)createFrom:(NSDictionary<NSString *, id> * _Nullable)response SWIFT_WARN_UNUSED_RESULT;
@end


/// Use <code>WinguLocations</code> to manage all triggers and locations inside wingu platform.<br/>
/// This class provide a way for managing zones and beacons in SDK. <br/>
/// <blockquote>
/// <em>Note:</em> <code>CLLocationManager</code> shouldn’t be deallocated if notifications are required.
///
/// </blockquote>
SWIFT_CLASS("_TtC17winguSDKEssential14WinguLocations")
@interface WinguLocations : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end







@class CLBeaconRegion;
@class CLRegion;

@interface WinguLocations (SWIFT_EXTENSION(winguSDKEssential)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didRangeBeacons:(NSArray<CLBeacon *> * _Nonnull)beacons inRegion:(CLBeaconRegion * _Nonnull)region;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didEnterRegion:(CLRegion * _Nonnull)region;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didExitRegion:(CLRegion * _Nonnull)region;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
@end






/// Callbacks from <code>CLLocationManagerDelegate</code> needed to make <code>WinguLocationManager</code> working
SWIFT_PROTOCOL("_TtP17winguSDKEssential22WinguLocationsDelegate_")
@protocol WinguLocationsDelegate
@optional
/// Authorization status gives you informations about current state of authorizationStatus.
/// \param authorizationStatus CLAuthorizationStatus, may be called several times, especially in a first run, when we ask user for permissions to use location.
///
- (void)authorizationStatus:(CLAuthorizationStatus)authorizationStatus;
@required
/// Returns always whole list of regions in range
/// \param regions Wingu regions
///
- (void)winguChannels:(NSArray<Channel *> * _Nonnull)channels;
@optional
/// You should reload view attached to beacon with this channel. Object will be always the same as in winguChannels(:) method and this method will always be called after callback from winguChannels(:).
/// \param channel updated channel
///
- (void)updatedContent:(Channel * _Nonnull)channel;
/// Whenever physical object change parameters this will return complete channel object with all updated parameters.
/// \param channel updated channel
///
- (void)updatePhysicalInfo:(Channel * _Nonnull)channel;
/// Some of the channels did change physical characteristics<br/>
/// If channels has some custom sorting or filtering this should be invoked in this place.<br/>
/// func <code>updatePhysicalInfo(:)</code> will provide more details of objects that changed.
/// <blockquote>
/// <em>Note</em> This is a direct callback from <code>CoreLocation</code> method for beacons ranging. It may be called very often depends on your settings.<br/>
///
/// </blockquote>
/// Example: If currently in range is one region this method will get called every second (the same as CoreLocation native). If there is two ranged regions this callback will get called twice in second.<br/>
- (void)updatePhysical;
/// Unseen collection of channels. If the end user never display content this will return collection of unseen, available regions in the area.<br/>
/// <blockquote>
/// <em>Note</em>: There is no point of using this method if only Essential part of SDK is used. This only works with winguSDKContent.<br/>
///
/// </blockquote>
/// Viewing content is driven by some rules:<br/>
/// <ul>
///   <li>
///     By view content action is understood by displaying wingu deck from winguSDKContent SDK<br/>
///   </li>
///   <li>
///     Whenever content updates in portal channel is treated as new one. It’s based on <code>Content.lastSeen</code> variable.<br/>
///   </li>
///   <li>
///     This is only valid for current locale. If language in portal was change for other language, this will not be returned here</br>
///   </li>
///   <li>
///     Channel will be returned once per discovery, if there is a need to check physical information further use <code>updatePhysicalInfo(_:)</code> method<br/>
///   </li>
/// </ul>
- (void)winguUnseenChannels:(NSArray<Channel *> * _Nonnull)channels;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
